CREATE TABLE IF NOT EXISTS results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  draw_time TEXT NOT NULL,
  sangam TEXT NOT NULL DEFAULT '',
  chetak TEXT NOT NULL DEFAULT '',
  super TEXT NOT NULL DEFAULT '',
  mp_deluxe TEXT NOT NULL DEFAULT '',
  bhagya_rekha TEXT NOT NULL DEFAULT '',
  diamond TEXT NOT NULL DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_date ON results(date);
